DELIMITER //

CREATE TRIGGER TG_BDS_INSERT_AUTOCODE BEFORE INSERT ON `dbo.property` FOR EACH ROW
BEGIN
    DECLARE ID INT;
    DECLARE PROPERTYTYPE VARCHAR(11);
    DECLARE NAMHT VARCHAR(2);
    DECLARE THANGHT VARCHAR(2);
    DECLARE MSBDS VARCHAR(11);
    DECLARE MAX_VAL INT;

    SET ID = NEW.ID;
    SET PROPERTYTYPE = NEW.Property_Type_ID;
    SET NAMHT = RIGHT(YEAR(CURDATE()), 2);
    SET THANGHT = LPAD(MONTH(CURDATE()), 2, '0');

    IF EXISTS (SELECT 1 FROM Property WHERE SUBSTRING(Property_Code, 5, 2) = NAMHT) THEN
        SET MAX_VAL = (SELECT MAX(RIGHT(Property_Code, 5)) FROM Property WHERE SUBSTRING(Property_Code, 5, 2) = NAMHT) + 1;
    ELSE
        SET MAX_VAL = 1;
    END IF;

    SET MSBDS = CONCAT('HD', THANGHT, NAMHT, LPAD(MAX_VAL, 5, '0'));
    SET NEW.Property_Code = MSBDS;
END //

DELIMITER ;
